export const SIGNIN = "SIGNIN";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const GET_SONGS = "GET_SONGS";
export const GET_SONGS_SUCCESS = "GET_SONGS_SUCCESS";
export const GET_SONGS_FAIL = "GET_SONGS_FAIL";

export const GET_SONGS_SEARCH = "GET_SONGS_SEARCH";
export const GET_SONGS_SEARCH_SUCCESS = "GET_SONGS_SEARCH_SUCCESS";
export const GET_SONGS_SEARCH_FAIL = "GET_SONGS_SEARCH_FAIL";

export const GET_DETAILS = "GET_DETAILS";
export const GET_DETAILS_SUCCESS = "GET_DETAILS_SUCCESS";
export const GET_DETAILS_FAIL = "GET_DETAILS_FAIL";

export const GET_FAVORITES = "GET_FAVORITES";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const GET_FAVORITES_FAIL = "GET_FAVORITES_FAIL";

export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const UPDATE_FAVORITES_SUCCESS = "UPDATE_FAVORITES_SUCCESS";
export const UPDATE_FAVORITES_FAIL = "UPDATE_FAVORITES_FAIL";

export const USER = "USER";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";